In [19]:
import pandas as pd

In [20]:
# Load dataset
df = pd.read_csv("../raw_dataset/DataCoSupplyChainDataset.csv", encoding="latin1")
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [21]:
df.shape

(180519, 53)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

# Customer Data

In [37]:
# ---------------------------
# 1. CUSTOMER CSV
# ---------------------------
customers_df = df[[
    "Customer Id",
    "Customer Fname",
    "Customer Lname",
    "Customer City",
    "Customer Country",
    "Customer State",
    "Customer Street",
    "Customer Zipcode",
    "Customer Segment",
    
]].drop_duplicates()

In [38]:
customers_df.shape

(20652, 9)

In [39]:
customers_df.head()

,Customer Id,Customer Fname,Customer Lname,Customer City,Customer Country,Customer State,Customer Street,Customer Zipcode,Customer Segment
0,20755,Cally,Holloway,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,725.0,Consumer
1,19492,Irene,Luna,Caguas,Puerto Rico,PR,2679 Rustic Loop,725.0,Consumer
2,19491,Gillian,Maldonado,San Jose,EE. UU.,CA,8510 Round Bear Gate,95125.0,Consumer
3,19490,Tana,Tate,Los Angeles,EE. UU.,CA,3200 Amber Bend,90027.0,Home Office
4,19489,Orli,Hendricks,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,725.0,Corporate

In [61]:
customers_df.to_csv("./data/customers.csv", index=False)

# Orders

In [40]:
orders_df = df[[
    'Order Id', 'Customer Id', 'order date (DateOrders)', 'Order Status','Order Region','Order State'
]].drop_duplicates()

In [41]:
orders_df.head()

,Order Id,Customer Id,order date (DateOrders),Order Status,Order Region,Order State
0,77202,20755,1/31/2018 22:56,COMPLETE,Southeast Asia,Java Occidental
1,75939,19492,1/13/2018 12:27,PENDING,South Asia,Rajastán
2,75938,19491,1/13/2018 12:06,CLOSED,South Asia,Rajastán
3,75937,19490,1/13/2018 11:45,COMPLETE,Oceania,Queensland
4,75936,19489,1/13/2018 11:24,PENDING_PAYMENT,Oceania,Queensland

In [42]:
orders_df.shape

(65752, 6)

In [62]:
orders_df.to_csv("./data/orders.csv", index=False)

# Order Items

In [63]:
order_items = df[[
    'Order Item Id','Order Id','Product Category Id', 'Order Item Quantity', 'Order Item Product Price', 
    'Order Item Total'
]].drop_duplicates()

In [64]:
order_items.shape

(180519, 6)

In [65]:
order_items.head()

,Order Item Id,Order Id,Product Category Id,Order Item Quantity,Order Item Product Price,Order Item Total
0,180517,77202,73,1,327.75,314.640015
1,179254,75939,73,1,327.75,311.359985
2,179253,75938,73,1,327.75,309.720001
3,179252,75937,73,1,327.75,304.809998
4,179251,75936,73,1,327.75,298.250000

In [66]:
order_items.to_csv("./data/order_items.csv", index=False)

# Products

In [67]:
products_df = df[[
    'Product Card Id', 'Product Category Id',
    'Product Name', 'Product Price'
]].drop_duplicates()

In [68]:
products_df.shape

(118, 4)

In [69]:
products_df.head()

,Product Card Id,Product Category Id,Product Name,Product Price
0,1360,73,Smart watch,327.750000
48,365,17,Perfect Fitness Perfect Rip Deck,59.990002
49,627,29,Under Armour Girls' Toddler Spine Surge Runni,39.990002
50,502,24,Nike Men's Dri-FIT Victory Golf Polo,50.000000
55,278,13,Under Armour Men's Compression EV SL Slide,44.990002

In [70]:
products_df.to_excel("./data/products.xlsx", index=False)

# Category

In [71]:
category_df = df[[
    'Category Id',
    'Category Name'
]].drop_duplicates()

In [72]:
category_df.head(20)

     Category Id         Category Name
0             73        Sporting Goods
48            17                Cleats
49            29         Shop By Sport
50            24       Women's Apparel
55            13           Electronics
56            12          Boxing & MMA
59             9      Cardio Equipment
61            41              Trade-In
62            37           Electronics
117           38      Kids' Golf Clubs
118           44    Hunting & Shooting
119            3   Baseball & Softball
138           18        Men's Footwear
143           43      Camping & Hiking
145           65  Consumer Electronics
146           62              Cameras
152           64             Computers
174            4            Basketball
175            2                Soccer
191           26        Girls' Apparel

In [73]:
category_df.to_excel("./data/category.xlsx", index=False)

# Shipping

In [76]:
shipping_df = df[[
    'Order Id', 'shipping date (DateOrders)',
    'Shipping Mode', 'Delivery Status'
]].drop_duplicates()

In [77]:
shipping_df.shape

(65752, 4)

In [78]:
shipping_df.shape

(65752, 4)

In [79]:
shipping_df.to_csv("./data/shipping.csv", index=False)